import { AiFillStar } from "react-icons/ai";

const data =[
    //suetas nike
    {
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEvRTRLTsnB02n1TrKEl_BnlACi9vFFQHIeA&s',
        title:'Sudadera para Básquetbol Nike ThermaFIT',
        star: <AiFillStar className="rating-star" />,
        reviews: "(411 reviews)",
        prevPrice: "$75,00",
        newPrice:'60',
        company:'Nike',
        color: "black",
        category: "suetas",
    },
    {
        img:'https://esportsparra.com/cdn/shop/products/sudadera-nike-sportswear-club-fleece-mens-hombre-842632_1080x.jpg?v=1722510486',
        title:'SUDADERA Nike CLUB Roja',
        star: <AiFillStar className="rating-star" />,
        reviews: "(954 reviews)",
        prevPrice: "$77,00",
        newPrice:'60',
        company:'Nike',
        color: "red",
        category: "suetas",
    },
    {
        img:'https://media.atmosferasport.es/243783-large_default/sudadera-nike-metallic-hbr-gifting-azul-infantil.jpg',
        title:'Sudadera Nike Metallic HBR Azul',
        star: <AiFillStar className="rating-star" />,
        reviews: "(411 reviews)",
        prevPrice: "$80,00",
        newPrice:'70',
        company:'Nike',
        color: "blue",
        category: "suetas",
    },
    {
        img:'https://media.foot-store.es/catalog/product/cache/image/1800x/9df78eab33525d08d6e5fb8d27136e95/b/v/bv2666-010-vpsrh001.jpg',
        title:'Sudadera Casual Nike Sportswear Negra',
        star: <AiFillStar className="rating-star" />,
        reviews: "(224 reviews)",
        prevPrice: "$70,00",
        newPrice:'60',
        company:'Nike',
        color: "black",
        category: "suetas",
    },
    {
        img:'https://zonaindoor.com/6138-large_default/sudadera-nike-sportswear-club-.jpg',
        title:'Sudadera Casual Nike Sportswear Blanca',
        star: <AiFillStar className="rating-star" />,
        reviews: "(418 reviews)",
        prevPrice: "$65,00",
        newPrice:'50',
        company:'Nike',
        color: "white",
        category: "suetas",
    },
    {
        img:'https://m.media-amazon.com/images/I/313tLybgS7L._AC_SY580_.jpg',
        title:'Sudadera Casual Nike  Roja',
        star: <AiFillStar className="rating-star" />,
        reviews: "(540 reviews)",
        prevPrice: "$72,00",
        newPrice:'66',
        company:'Nike',
        color: "red",
        category: "suetas",
    },
    {
        img:'https://img1.wsimg.com/isteam/ip/23151562-d33c-413c-9407-244f77223ef1/ols/3110D633-6E71-4654-8565-2352BABB3B10.jpeg/:/rs=w:1200,h:1200',
        title:'Sudadera Casual Nike Azul',
        star: <AiFillStar className="rating-star" />,
        reviews: "(540 reviews)",
        prevPrice: "$80,00",
        newPrice:'70',
        company:'Nike',
        color: "blue",
        category: "suetas",
    },
    //camisas nike
    {
        img:'https://gfx.r-gol.com/media/res/products/52/146052/465x605/koszulka-nike-dry-academy-21-top-ss_1.png',
        title:'Camiseta Nike azul',
        star: <AiFillStar className="rating-star" />,
        reviews: "(487 reviews)",
        prevPrice: "$40,00",
        newPrice:'50',
        company:'Nike',
        color: "blue",
        category: "camisas",
    },
    {
        img:'https://img.freepik.com/vector-premium/logotipo-nike-maqueta-camiseta-colores-azules-maqueta-camiseta-realista-mangas-cortas-plantilla-camiseta-blanco-espacio-vacio-diseno-marca-nike_661108-7762.jpg',
        title:'Camiseta Nike azul degradado',
        star: <AiFillStar className="rating-star" />,
        reviews: "(105 reviews)",
        prevPrice: "$55,00",
        newPrice:'50',
        company:'Nike',
        color: "blue",
        category: "camisas",
    },{
        img:'https://i1.t4s.cz//products/725891-410/98118-960.webp',
        title:'Camiseta Nike azul Entrenamiento',
        star: <AiFillStar className="rating-star" />,
        reviews: "(441 reviews)",
        prevPrice: "$45,00",
        newPrice:'40',
        company:'Nike',
        color: "blue",
        category: "camisas",
    },
    {
        img:'https://www.thefutbolstore.com.ar/uploads/v2/product/hi/725892_657_A.jpg',
        title:'Camiseta Nike Striker IV Roja',
        star: <AiFillStar className="rating-star" />,
        reviews: "(105 reviews)",
        prevPrice: "$60,00",
        newPrice:'50',
        company:'Nike',
        color: "red",
        category: "camisas",
    },
    {
        img:'https://www.padel-point.com/dw/image/v2/BBDP_PRD/on/demandware.static/-/Sites-master-catalog/default/dw96907b13/images/004/454/52036000_000.jpg?q=80&sw=2000',
        title:'Camiseta Nike Dri-Fit Roja',
        star: <AiFillStar className="rating-star" />,
        reviews: "(115 reviews)",
        prevPrice: "$65,00",
        newPrice:'50',
        company:'Nike',
        color: "red",
        category: "camisas",
    },
    {
        img:'https://www.deportesmegra.com/2227168-large_default/camisetas-nike-m-nk-df-park20-ss-top.jpg',
        title:'Camiseta Nike Roja logo grande',
        star: <AiFillStar className="rating-star" />,
        reviews: "(105 reviews)",
        prevPrice: "$90,00",
        newPrice:'60',
        company:'Nike',
        color: "red",
        category: "camisas",
    },
    {
        img:'https://i.ebayimg.com/thumbs/images/g/XhkAAOSwQtpioTuV/s-l1200.jpg',
        title:'Camiseta Nike blanca just do it',
        star: <AiFillStar className="rating-star" />,
        reviews: "(574 reviews)",
        prevPrice: "$200,00",
        newPrice:'70',
        company:'Nike',
        color: "white",
        category: "camisas",
    },
    {
        img:'https://m.media-amazon.com/images/I/31qp9J+qUaL._AC_UY1000_.jpg',
        title:'Camiseta Nike blanca compresion',
        star: <AiFillStar className="rating-star" />,
        reviews: "(546 reviews)",
        prevPrice: "$70,00",
        newPrice:'50',
        company:'Nike',
        color: "white",
        category: "camisas",
    },
    {
        img:'https://i.etsystatic.com/23630957/r/il/1e61aa/4114902063/il_570xN.4114902063_r4f0.jpg',
        title:'Camiseta Nike blanca logo grande',
        star: <AiFillStar className="rating-star" />,
        reviews: "(546 reviews)",
        prevPrice: "$70,00",
        newPrice:'60',
        company:'Nike',
        color: "white",
        category: "camisas",
    },
    {
        img:'https://static.sprintercdn.com/products/0375756/camiseta-nike_0375756_00_4_970776862.jpg',
        title:'Camiseta Nike negra casual',
        star: <AiFillStar className="rating-star" />,
        reviews: "(715 reviews)",
        prevPrice: "$60,00",
        newPrice:'50',
        company:'Nike',
        color: "black",
        category: "camisas",
    },
    {
        img:'https://http2.mlstatic.com/D_NQ_NP_734278-MLA50880622543_072022-O.webp',
        title:'Camiseta Nike negra casual',
        star: <AiFillStar className="rating-star" />,
        reviews: "(453 reviews)",
        prevPrice: "$80,00",
        newPrice:'50',
        company:'Nike',
        color: "black",
        category: "camisas",
    },
    {
        img:'https://down-co.img.susercontent.com/file/4b1a0c97fbf5a6073f1c402ac0fa59c5',
        title:'Camiseta Nike negra casual big swoosh',
        star: <AiFillStar className="rating-star" />,
        reviews: "(322 reviews)",
        prevPrice: "$80,00",
        newPrice:'60',
        company:'Nike',
        color: "black",
        category: "camisas",
    },
    //pantalones nike
    {
        img:'https://f.fcdn.app/imgs/9a2721/www.zooko.com.uy/zoo/b214/original/catalogo/NKFB7687-010-1/1920-1200/pantalon-nike-club-black.jpg',
        title:'Pantalon Nike club negro ',
        star: <AiFillStar className="rating-star" />,
        reviews: "(638 reviews)",
        prevPrice: "$70,00",
        newPrice:'50',
        company:'Nike',
        color: "black",
        category: "pantalones",
    },
    {
        img:'https://rekordsport.es/uploads/photo/image/261/gallery_A00705_1.JPG',
        title:'Pantalon Nike academy negro ',
        star: <AiFillStar className="rating-star" />,
        reviews: "(150 reviews)",
        prevPrice: "$55,00",
        newPrice:'50',
        company:'Nike',
        color: "black",
        category: "pantalones",
    },
    {
        img:'https://www.stockcenter.com.ar/on/demandware.static/-/Sites-dabra-catalog/default/dw3957e21e/products/NI_AR2940-100/NI_AR2940-100-1.JPG',
        title:'Pantalon Nike track blanco ',
        star: <AiFillStar className="rating-star" />,
        reviews: "(418 reviews)",
        prevPrice: "$60,00",
        newPrice:'50',
        company:'Nike',
        color: "white",
        category: "pantalones",
    },
    {
        img:'https://www.moov.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw0b6fba95/products/NI_CU9200-902/NI_CU9200-902-1.JPG',
        title:'Pantalon Nike sportswear blanco ',
        star: <AiFillStar className="rating-star" />,
        reviews: "(214 reviews)",
        prevPrice: "$60,00",
        newPrice:'50',
        company:'Nike',
        color: "white",
        category: "pantalones",
    },

    {
        img:'https://media.futbolmania.com/media/catalog/product/cache/1/image/0f330055bc18e2dda592b4a7c3a0ea22/C/J/CJ4877-657_imagen-del-pantalon-de-paseo-chandal-nike-swoosh-rojo_1_fontal.jpg',
        title:'Pantalon Nike sportswear rojo double swoosh ',
        star: <AiFillStar className="rating-star" />,
        reviews: "(334 reviews)",
        prevPrice: "$60,00",
        newPrice:'50',
        company:'Nike',
        color: "red",
        category: "pantalones",
    },
    {
        img:'https://dripchileno.cl/wp-content/uploads/2024/04/d52861e8-d57e-4619-abe8-d0eba83e50cd.png',
        title:'Pantalon Nike tech Rojo ',
        star: <AiFillStar className="rating-star" />,
        reviews: "(214 reviews)",
        prevPrice: "$60,00",
        newPrice:'50',
        company:'Nike',
        color: "red",
        category: "pantalones",
    },

    {
        img:'https://www.stockcenter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw0e7c11a0/products/NI_AO0745-407/NI_AO0745-407-1.JPG',
        title:'Pantalon Nike Dry azul ',
        star: <AiFillStar className="rating-star" />,
        reviews: "(486 reviews)",
        prevPrice: "$95,00",
        newPrice:'70',
        company:'Nike',
        color: "blue",
        category: "pantalones",
    },
    {
        img:'https://www.deportescasais.es/uploads/photo/image/5050/gallery_A03239_ayyW2q5a.JPG',
        title:'Pantalon Nike Air azul',
        star: <AiFillStar className="rating-star" />,
        reviews: "(641 reviews)",
        prevPrice: "$60,00",
        newPrice:'50',
        company:'Nike',
        color: "blue",
        category: "pantalones",
    },

    //tenis nike
    {
        img:'https://chelseaio.vtexassets.com/arquivos/ids/509711/FN5924-001_1.jpg?v=638537123091130000',
        title:'Air Force One negras',
        star: <AiFillStar className="rating-star" />,
        reviews: "(882 reviews)",
        prevPrice: "$90,00",
        newPrice:'70',
        company:'Nike',
        color: "black",
        category: "zapatos",
    },
    {
        img:'https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/a29e735f-6b9f-44a3-ae99-1f0da7ff39b4/W+NIKE+CORTEZ+23+PREMIUM.png',
        title:'Nike cortez negras',
        star: <AiFillStar className="rating-star" />,
        reviews: "(550 reviews)",
        prevPrice: "$85,00",
        newPrice:'80',
        company:'Nike',
        color: "black",
        category: "zapatos",
    },
    {
        img:'https://i.ebayimg.com/images/g/eBgAAOSwnBllMEd0/s-l1600.jpg',
        title:'Nike Air max 97 negras',
        star: <AiFillStar className="rating-star" />,
        reviews: "(688 reviews)",
        prevPrice: "$55,00",
        newPrice:'50',
        company:'Nike',
        color: "black",
        category: "zapatos",
    },

    //
    {
        img:'https://tuofferta.com/wp-content/uploads/2022/11/Zapato-Force-One-Blanco-para-mujer-y-hombre-Trainers-Sneakers-online-tenis-zapatillas-shoes-tienda-en-colombia-en-oferta-9.jpg',
        title:'Air Force One blancas',
        star: <AiFillStar className="rating-star" />,
        reviews: "(968 reviews)",
        prevPrice: "$90,00",
        newPrice:'70',
        company:'Nike',
        color: "white",
        category: "zapatos",
    },
    {
        img:'https://i.ebayimg.com/thumbs/images/g/KwAAAOSwBKllxiC3/s-l1200.jpg',
        title:'Nike cortez blancas',
        star: <AiFillStar className="rating-star" />,
        reviews: "(720 reviews)",
        prevPrice: "$85,00",
        newPrice:'80',
        company:'Nike',
        color: "white",
        category: "zapatos",
    },
    {
        img:'https://thekingoftheshoes.weebly.com/uploads/1/2/4/2/124263922/s998041992412278862_p242_i6_w906.jpeg',
        title:'Nike Air max 97 blancas',
        star: <AiFillStar className="rating-star" />,
        reviews: "(445 reviews)",
        prevPrice: "$80,00",
        newPrice:'60',
        company:'Nike',
        color: "white",
        category: "zapatos",
    },

    //
    {
        img:'https://static.mercdn.net/item/detail/orig/photos/m59098689190_7.jpg?1727607321',
        title:'Air Force One rojas',
        star: <AiFillStar className="rating-star" />,
        reviews: "(741 reviews)",
        prevPrice: "$90,00",
        newPrice:'70',
        company:'Nike',
        color: "red",
        category: "zapatos",
    },
    {
        img:'https://i.ebayimg.com/thumbs/images/g/7-wAAOSwP3RlB24x/s-l1200.jpg',
        title:'Nike cortez Rojas',
        star: <AiFillStar className="rating-star" />,
        reviews: "(525 reviews)",
        prevPrice: "$85,00",
        newPrice:'80',
        company:'Nike',
        color: "red",
        category: "zapatos",
    },
    {
        img:'https://i.ebayimg.com/thumbs/images/g/kIMAAOSwtutnDR21/s-l1200.jpg',
        title:'Nike Air max 97 Rojas',
        star: <AiFillStar className="rating-star" />,
        reviews: "(342 reviews)",
        prevPrice: "$80,00",
        newPrice:'60',
        company:'Nike',
        color: "red",
        category: "zapatos",
    },
    //
    {
        img:'https://www.manelsanchez.com/uploads/media/images/800x800/596728-421.manelsanchez_.2_.jpg',
        title:'Air Force One azul',
        star: <AiFillStar className="rating-star" />,
        reviews: "(801 reviews)",
        prevPrice: "$90,00",
        newPrice:'70',
        company:'Nike',
        color: "blue",
        category: "zapatos",
    },
    {
        img:'https://images.stockx.com/images/Nike-Cortez-Nylon-DSM-Blue.png?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&q=90&dpr=2&trim=color&updated_at=1626898087',
        title:'Nike cortez azul',
        star: <AiFillStar className="rating-star" />,
        reviews: "(445 reviews)",
        prevPrice: "$85,00",
        newPrice:'80',
        company:'Nike',
        color: "blue",
        category: "zapatos",
    },
    {
        img:'https://i.ebayimg.com/thumbs/images/g/XEAAAOSwtQVmV~K~/s-l1200.jpg',
        title:'Nike Air max 97 azul',
        star: <AiFillStar className="rating-star" />,
        reviews: "(805 reviews)",
        prevPrice: "$80,00",
        newPrice:'60',
        company:'Nike',
        color: "blue",
        category: "zapatos",
    },
];

export default data;